
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author w7
 */
public class BuscaGUI extends javax.swing.JFrame {

    /**
     * Creates new form CadastroClienteGUI
     */
    public BuscaGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLcodigo = new javax.swing.JLabel();
        jLtitulo = new javax.swing.JLabel();
        jTcodigo = new javax.swing.JTextField();
        jLnome = new javax.swing.JLabel();
        jTnome = new javax.swing.JTextField();
        jLcpf = new javax.swing.JLabel();
        jTcpf = new javax.swing.JTextField();
        jLtelefone = new javax.swing.JLabel();
        jTtelefone = new javax.swing.JTextField();
        jLlogradouro = new javax.swing.JLabel();
        jTlogradouro = new javax.swing.JTextField();
        jLnumero = new javax.swing.JLabel();
        jTnumero = new javax.swing.JTextField();
        jLbairro = new javax.swing.JLabel();
        jLcidade = new javax.swing.JLabel();
        jLestado = new javax.swing.JLabel();
        jTbairro = new javax.swing.JTextField();
        jTcidade = new javax.swing.JTextField();
        jTestado = new javax.swing.JTextField();
        jBbuscar = new javax.swing.JButton();
        jBlimpar = new javax.swing.JButton();
        jBsair = new javax.swing.JButton();
        jBexcluir = new javax.swing.JButton();
        jBalterar = new javax.swing.JButton();
        jCopcaoBusca = new javax.swing.JComboBox<>();
        jTentBuscar = new javax.swing.JTextField();
        panel = new javax.swing.JPanel();



        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLcodigo.setText("Codigo:");

        jLtitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLtitulo.setText("Busca de Cliente");
        jLtitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTcodigo.setEditable(false);

        jLnome.setText("Nome:");

        jTnome.setEditable(false);

        jLcpf.setText("CPF:");

        jTcpf.setEditable(false);
        jTcpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcpfActionPerformed(evt);
            }
        });

        jLtelefone.setText("Telefone:");

        jTtelefone.setEditable(false);

        jLlogradouro.setText("Logradouro:");

        jTlogradouro.setEditable(false);
        jTlogradouro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTlogradouroActionPerformed(evt);
            }
        });

        jLnumero.setText("Nº:");

        jTnumero.setEditable(false);

        jLbairro.setText("Bairro:");

        jLcidade.setText("Cidade:");

        jLestado.setText("Estado:");

        jTbairro.setEditable(false);
        jTbairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTbairroActionPerformed(evt);
            }
        });

        jTcidade.setEditable(false);
        jTcidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcidadeActionPerformed(evt);
            }
        });

        jTestado.setEditable(false);

        jBbuscar.setText("Buscar");
        jBbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarActionPerformed(evt);
            }
        });

        jBlimpar.setText("Limpar");
        jBlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlimparActionPerformed(evt);
            }
        });

        jBsair.setText("Sair");
        jBsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsairActionPerformed(evt);
            }
        });

        jBexcluir.setText("Excluir");
        jBexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBexcluirActionPerformed(evt);
            }
        });

        jBalterar.setText("Alterar");
        jBalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBalterarActionPerformed(evt);
            }
        });

        jCopcaoBusca.setEditable(true);
        jCopcaoBusca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Opção da Busca", "Codigo", "CPF", "Todos" }));
        jCopcaoBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCopcaoBuscaActionPerformed(evt);
            }
        });

        jTentBuscar.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLnome)
                        .addGap(18, 18, 18)
                        .addComponent(jTnome))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLcpf)
                        .addGap(27, 27, 27)
                        .addComponent(jTcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLtelefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTtelefone))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLlogradouro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTlogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLnumero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTnumero, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLbairro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTbairro))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLcidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTcidade))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBalterar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLestado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBlimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addComponent(jBsair, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTestado)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLcodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jCopcaoBusca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTentBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLtitulo)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBbuscar)
                    .addComponent(jCopcaoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTentBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLcodigo)
                    .addComponent(jTcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLnome)
                    .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLcpf)
                    .addComponent(jTcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLtelefone)
                    .addComponent(jTtelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLlogradouro)
                    .addComponent(jTlogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLnumero)
                    .addComponent(jTnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbairro)
                    .addComponent(jTbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLcidade)
                    .addComponent(jLestado)
                    .addComponent(jTcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBlimpar)
                    .addComponent(jBsair)
                    .addComponent(jBexcluir)
                    .addComponent(jBalterar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTcpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTcpfActionPerformed

    private void jTlogradouroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTlogradouroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTlogradouroActionPerformed

    private void jTbairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTbairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTbairroActionPerformed

    private void jTcidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTcidadeActionPerformed

    private void jBbuscarActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        
    
//    private void jBinserirActionPerformed(java.awt.event.ActionEvent evt) {
//        
//    	ativarCampos();
//        buscarDados();
//        
//    }//jBinserirActionPerformed

    private void jBsairActionPerformed(java.awt.event.ActionEvent evt) {
    	
    	sair();
    	
    }//jBsairActionPerformed

    private void jBlimparActionPerformed(java.awt.event.ActionEvent evt) {
    	
        limparCampos();
        
    }//jBlimparActionPerformed

    private void jBexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBexcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBexcluirActionPerformed

    private void jBalterarActionPerformed(java.awt.event.ActionEvent evt) {
       
    	alterarDados();
       
    }//jBalterarActionPerformed

    private void jCopcaoBuscaActionPerformed(java.awt.event.ActionEvent evt) {
        
    	if(jCopcaoBusca.getSelectedIndex() == 1){
            limparCampos();
            jTentBuscar.setEnabled(true);
            jTentBuscar.setText("Digite Codigo ...");
            ativarCampos();
        }//if
        
        if(jCopcaoBusca.getSelectedIndex() == 2){
             limparCampos();
             jTentBuscar.setText("Digite CPF ...");
             ativarCampos();
        }//if
        else if (jCopcaoBusca.getSelectedIndex() == 3){
            BuscaModificadaGUI busca = new BuscaModificadaGUI() ;
            busca.setVisible(true);
            limparCampos();
            
        }//elseif
        
    }//jCopcaoBuscaActionPerformed    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroClienteGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBalterar;
    private javax.swing.JButton jBbuscar;
    private javax.swing.JButton jBexcluir;
    private javax.swing.JButton jBlimpar;
    private javax.swing.JButton jBsair;
    private javax.swing.JComboBox<String> jCopcaoBusca;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLbairro;
    private javax.swing.JLabel jLcidade;
    private javax.swing.JLabel jLcodigo;
    private javax.swing.JLabel jLcpf;
    private javax.swing.JLabel jLestado;
    private javax.swing.JLabel jLlogradouro;
    private javax.swing.JLabel jLnome;
    private javax.swing.JLabel jLnumero;
    private javax.swing.JLabel jLtelefone;
    private javax.swing.JLabel jLtitulo;
    private javax.swing.JTextField jTbairro;
    private javax.swing.JTextField jTcidade;
    private javax.swing.JTextField jTcodigo;
    private javax.swing.JTextField jTcpf;
    private javax.swing.JTextField jTentBuscar;
    private javax.swing.JTextField jTestado;
    private javax.swing.JTextField jTlogradouro;
    private javax.swing.JTextField jTnome;
    private javax.swing.JTextField jTnumero;
    private javax.swing.JTextField jTtelefone;
    static javax.swing.JPanel panel;
    static BuscaGUI frameBusca;
    // End of variables declaration//GEN-END:variables

    public void inserirDados(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost/BDCadastro", "root", "");
            java.sql.Statement stmt = con.createStatement();
            
            int cadMat = Integer.parseInt(jTcodigo.getText());
            String cadNome = jTnome.getText();
            String cadCPF = jTcpf.getText();
            String cadTelefone = jTtelefone.getText();
            String cadLogradouro = jTlogradouro.getText();
            String cadNumero = jTnumero.getText();
            String cadBairro = jTbairro.getText();
            String cadCidade = jTcidade.getText();
            String cadEstado = jTestado.getText();
            
            /*mudanca de sintaxe 
            //https://www.oficinadanet.com.br/artigo/java/criando-um-cadastro-de-usuario-em-java
            String sql = "INSERT INTO TabFicha (Matricula, Nome, CPF, Telefone, Logradoura, Numero, Bairro , Cidade, Estado) VALUES (?,?,?,?,?,?,?,?,? )";
            stmt.setString(1, CadMat);// tratar numero
            stmt.setString(2, cadNome);
            stmt.setString(3, cadCPF);*/
            stmt.executeUpdate("insert into TabFicha (Matricula, Nome, CPF, Telefone, Logradouro, Numero, Bairro, Cidade, Estado) values ('"
                + cadMat
                + "','"
                + cadNome
                + "','"
                + cadCPF
                + "','"
                + cadTelefone
                + "','"
                + cadLogradouro
                + "','"
                + cadNumero
                + "','"
                + cadBairro
                + "','"
                + cadCidade
                + "','"
                + cadEstado
                + "')");
            
            JOptionPane.showMessageDialog(null, "Dados da Matricula " + cadMat + "Salvos!");
            limparCampos();
           
            con.close();
        }//try
        catch(SQLException erro) {
        	JOptionPane.showMessageDialog(null, "Erro comando SQL " + erro.getMessage());
        }//catch
        catch (ClassNotFoundException erro) {
        	JOptionPane.showMessageDialog(null, "ClassNotFoundException - Driver não encontrado!\r"+ erro.getMessage());
        }//catch
        
    }//inserirDados
    
    
    public void limparCampos() {
        
    	jTentBuscar.setText("");
    	jTcodigo.setText("");
    	jTnome.setText("");
    	jTcpf.setText("");
    	jTtelefone.setText("");
    	jTlogradouro.setText("");
    	jTnumero.setText("");
    	jTbairro.setText("");
    	jTcidade.setText("");
        jTestado.setText("");
    	
    }//limparCampos 
    
    public void ativarCampos(){
        
        jTentBuscar.setEnabled(true);
    	jTcodigo.setEnabled(true);
    	jTnome.setEnabled(true);
    	jTcpf.setEnabled(true);
    	jTtelefone.setEnabled(true);
    	jTlogradouro.setEnabled(true);
    	jTnumero.setEnabled(true);
    	jTbairro.setEnabled(true);
    	jTcidade.setEnabled(true);
        jTestado.setEnabled(true);
        
        jTentBuscar.setEditable(true);
    	jTcodigo.setEditable(true);
    	jTnome.setEditable(true);
    	jTcpf.setEditable(true);
    	jTtelefone.setEditable(true);
    	jTlogradouro.setEditable(true);
    	jTnumero.setEditable(true);
    	jTbairro.setEditable(true);
    	jTcidade.setEditable(true);
        jTestado.setEditable(true);
        
        System.out.println("jTestado.setEnabled(true)");
        
    }//ativarCampos

    public void buscarDados(){
        boolean consulta = true;
        try {
        	Class.forName("com.mysql.jdbc.Driver");
        	java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost/BDCadastro", "root", "");
        	java.sql.Statement stmt = con.createStatement();
        	
        	int buscaCodigo = Integer.parseInt(jTentBuscar.getText());
        	//String buscaCPF = jTentBuscar.getText();
        	String buscaCPF = jTcpf.getText();
        	
        	ResultSet rs = null;
        	
        	if(jCopcaoBusca.getSelectedIndex()==0) {
        		JOptionPane.showMessageDialog(null, "Escolha opção de Busca!");
        	}//if
        	else if(jCopcaoBusca.getSelectedIndex()==1) {
        		rs = stmt.executeQuery("Select * from TabFciha where Matricula = " + buscaCodigo);
        		
        		while (rs.next()) {
        		
        			int mat = rs.getInt("Matricula");
        			jTcodigo.setText(String.valueOf(mat));
        			
        			jTnome.setText(rs.getString("Nome"));
        			jTcpf.setText(rs.getString("CPF"));
        			jTtelefone.setText(rs.getString("Telefone"));
        			jTlogradouro.setText(rs.getString("Logradouro"));
        			jTnumero.setText(rs.getString("Numero"));
        			jTbairro.setText(rs.getString("Bairro"));
        			jTcidade.setText(rs.getString("Cidade"));
        			jTestado.setText(rs.getString("Estado"));
        			
        			consulta = false;
        			JOptionPane.showMessageDialog(null, "Dados encontrados!");
        			
        			
        		}//while
        		
        	}//else if
        	else if(jCopcaoBusca.getSelectedIndex() == 2) {
        		rs = stmt.executeQuery("Select * from TabFicha where CPF = " + buscaCPF);
        		
        		while(rs.next()) {
        			String cpf = rs.getString("CPF");
        			jTcpf.setText(cpf);
        			
        			jTnome.setText(rs.getString("Nome"));
        			jTtelefone.setText(rs.getString("Telefone"));
        			jTlogradouro.setText(rs.getString("Logradouro"));
        			jTnumero.setText(rs.getString("Numero"));
        			jTbairro.setText(rs.getString("Bairro"));
        			jTcidade.setText(rs.getString("Cidade"));
        			jTestado.setText(rs.getString("Estado"));
        			
        			consulta = false;
        			JOptionPane.showMessageDialog(null, "Dados encontrados!");
        			
        		}//while
        		
        	}//else if
        	
        	if(consulta) {
        		JOptionPane.showMessageDialog(null, "Dados NÃO encontrados!");
        	}//if
        	
        	rs.close();
        	stmt.close();
        	con.close();
        	
        	
        }//try
        catch (SQLException erro) {
        	JOptionPane.showMessageDialog(null,  "Erro comando SQL" + erro.getMessage());
        }//catch
        catch (ClassNotFoundException erro) {
        	JOptionPane.showMessageDialog(null, "Driver NÃO Encontrado");
        }//catch
        
    }//BurcarDados
    
    public void alterarDados() {
    	try {
    		Class.forName("com.mysql.jdbc.Driver");
    		
    		java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost/BDCadastro", "root", "" );
    		
    		java.sql.Statement stmt = con.createStatement();
    		
    		int consMatricula = Integer.parseInt(jTentBuscar.getText());
    		String consCPF = jTentBuscar.getText();
    		
    		int cadMat = Integer.parseInt(jTcodigo.getText());
    		String cadNome = jTnome.getText();
    		String cadCPF = jTcpf.getText();
    		String cadTelefone = jTtelefone.getText();
    		String cadLogradouro = jTlogradouro.getText();
    		int cadNumero = Integer.parseInt(jTnumero.getText());
    		String cadBairro = jTbairro.getText();
    		String cadCidade = jTcidade.getText();
    		String cadEstado = jTestado.getText();
    		
    		if(jCopcaoBusca.getSelectedIndex() == 1) {
    			
    			int registro = stmt.executeUpdate("update TabFicha set "
    					+ "Nome= '" + cadNome + "',CPF='" + cadCPF + "',Telefone='" + cadTelefone + "',Logradouro='" + cadLogradouro
    					+ "',Numero='" + cadNumero + "',Bairro='" + cadBairro + "',Cidade='" + cadCidade + "',Estado='" + cadEstado + "',Matricula='" + cadMat  
    					+ "' where Matricula=" + consMatricula);
    		
    			if(registro!=0 ) {
        			JOptionPane.showMessageDialog(null, "Dados Alterados!");
        		}//if
    			else {
    				JOptionPane.showMessageDialog(null, "Dados NÃO Alterados!");
    			}//else
    			
    			stmt.close();
    			con.close();
    			
    		}//if
    		else if(jCopcaoBusca.getSelectedIndex() == 2) {
    			
    			int registro = stmt.executeUpdate("update TabFicha set "
    					+ "Nome= '" + cadNome + "',CPF='" + cadCPF + "',Telefone='" + cadTelefone + "',Logradouro='" + cadLogradouro
    					+ "',Numero='" + cadNumero + "',Bairro='" + cadBairro + "',Cidade='" + cadCidade + "',Estado='" + cadEstado + "',Matricula='" + cadMat  
    					+ "' where CPF=" + consCPF);
    			
    			if(registro!=0) {
    				JOptionPane.showMessageDialog(null, "Dados Alterados!");
    			}//if
    			else {
    				JOptionPane.showMessageDialog(null, "Dados NÃO Alterados!");
    			}//else
    			
    			stmt.close();
    			con.close();
    			
    		}//else if
    		
    	}//try
    	catch (SQLException erro) {
        	JOptionPane.showMessageDialog(null,  "Erro comando SQL" + erro.getMessage());
        }//catch
        catch (ClassNotFoundException erro) {
        	JOptionPane.showMessageDialog(null, "Driver NÃO Encontrado");
        }//catch
    		
    }//alterarDados
    
    public void excluirDados() {
    	
    	try {
    		
    		Class.forName("com.mysql.jdbc.Driver");
    		java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost/BDCadastro", "root", "");
    		java.sql.Statement stmt = con.createStatement();
    		
    		int excluirMatricula = Integer.parseInt(jTentBuscar.getText());
    		int registro = stmt.executeUpdate("delete from Tabficha where Matricula="+ excluirMatricula);
    		
    		if(registro != 0) {
    			JOptionPane.showMessageDialog(null,"Dados da Matricula " + excluirMatricula + "Excluídos!");
    		}//if
    		else {
    			JOptionPane.showMessageDialog(null,  "Dados NÃO Excluídos!");
    		}//else
    		
    		stmt.close();
    		
    		limparCampos();
    		
    		con.close();
    		
    	}//try
    	catch(SQLException erro) {
    		JOptionPane.showMessageDialog(null,  "Erro Cmdo SQL" + erro.getMessage());
    	}//catch
    	catch(ClassNotFoundException erro){
    		JOptionPane.showMessageDialog(null,  "Driver NÃO Encontrado!");
    	}//catch
    	
    	
    }//excluirDados

    private void sair() {
        this.dispose(); 
    }
    
}//class
